php:
    container_name: sci-php
    build: docker/php
    volumes:
        - ./app:/app
        - ./app/var/cache:/app/var/cache
        - /tmp
    links:
        - mysql
nginx:
  container_name: sci-nginx
  build: docker/nginx
  volumes:
      - ./app:/app
  links:
      - php
  environment:
    VIRTUAL_HOST: sci.local
  ports:
    - "80:80"

mysql:
    build: docker/mysql
    container_name: sci-mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
     - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
